### ISSUE TITLE
compound type definitions.

### ISSUE THREAD

**Issue by petethecat** [AOMediaCodec/av1-spec#111]
In the spec, compound_type is defined as wedge (0), diffwtd (1), average (2), intra (3), distance (4).
But in the code (enums.h), it is defined as:

typedef enum {
   COMPOUND_AVERAGE,
   COMPOUND_WEDGE,
   COMPOUND_DIFFWTD,
   COMPOUND_TYPES,
} COMPOUND_TYPE;

So the code doesn't have COMPOUND_INTRA  or COMPOUND_DISTANCE mode. And constants for average/wedge/diffwtd are also different. Is the spec going to follow the code and remove intra/distance modes?

Thanks.

**Comment by peterderivaz** [comment]
This was an intentional rearrangement to make the specification easier to understand.

(The code reads the compound_type syntax element (returning wedge/diffwtd) and then adds 1 to it to offset to the required enums.  If we did this in the spec we would have to define a new type of variable CompoundType which was offset from the syntax element. Also the code does use the distance and intra compound prediction, but they are represented in a more complicated way in the code.)
