### ISSUE TITLE
Discrepancy between spec and reference software

### ISSUE THREAD

**Issue by chengchen-google** [AOMediaCodec/av1-spec#197]
In spec 7.11.3.8 Warp estimation process:
midY = MiRow * 4 + h4 * 2 - 1
midX = MiCol * 4 + w4 * 2 - 1
suy = midY * 8
sux = midX * 8

That's different from libaom, av1/common/warped_motion.c: find_affine_int():
  const int bw = block_size_wide[bsize];
  const int bh = block_size_high[bsize];
  const int rsuy = (AOMMAX(bh, MI_SIZE) / 2 - 1);
  const int rsux = (AOMMAX(bw, MI_SIZE) / 2 - 1);
  const int suy = rsuy * 8;
  const int sux = rsux * 8;

I believe the reference software is correct, and the spec should change to:
midY = MiRow * 4 + h4 * 2 - 1
midX = MiCol * 4 + w4 * 2 - 1
suy = (h4 * 2 - 1) * 8
sux = (w4 * 2 - 1) * 8

**Comment by peterderivaz** [comment]
I think both reference software and spec are correct, but in slightly different ways.

For efficiency, the reference software uses a mixture of coordinate systems in find_affine_int:

rsux and rsuy (I assume standing for relative sux and suy?) are relative to the top left of the block.
mi_row and mi_col are relative to the top left of the frame
isuy and isux are relative to the top left of the frame.
suy and sux are relative to the top left of the block.
pts1 and pts2 are relative to the top left of the block.

For simplicity, the specification always uses absolute coordinates in the warp estimation process:

In particular, sux/suy and CandList[i][0/1] are relative to the top left of the frame. 

The reason this doesn't result in a normative difference is because all the calculation is based on the difference of two values.  Therefore the constant offset cancels out.

**Comment by chengchen-google** [comment]
Thanks for your explanation. It makes sense.

**Comment by agrange** [comment]
Issue seems to have been addressed - no action required - so I will close.

Please reopen if there is anything else to consider.
