### ISSUE TITLE
extend_frame is missing in the specification

### ISSUE THREAD

**Issue by joshuazhu78** [AOMediaCodec/av1-spec#238]
Trying to implement the decoder based on the specification. When trying to compare the decoding results with the reference decoder, found below mismatch between the reference decoder and the specification.

In restoration.c function av1_loop_restoration_filter_frame_init, there is a function extend_frame that copies several rows at bottom edge to outside of the bottom edge. And this will further impact pixel values at bottom edge. 

Could not find this process in AV1 specification.

And in 7.11.3.4. Block inter prediction process, the lastY value should also be changed accordingly as below:

if (plane == 0 && !mv[0] && !mv[1]) lastY = lastY + 8;

After having these two changes implemented, the decoding results match with the reference decoder.

**Comment by peterderivaz** [comment]
Hi Joshua,

1) extend_frame
Implementations have a choice of whether to extend when reading the pixels (hardware implementations will normally do this) or extend frame borders (software implementations will normally do this).

The reference code shows how to extend with frame borders, while the specification shows how to extend when reading the pixels (so that an implementer can see both styles).  The intention, of course, is that both methods should behave identically so it is concerning if you do not think this is true.

The extension in loop restoration happens within [get_source_sample](http://av1-draft-spec.argondesign.com/av1-spec/#get-source-sample-process)

Note that the y coordinate is clipped to PlaneEndY, which is based on the FrameHeight.

Can you check you have implemented this clip please?


2) Block inter prediction

This part has some history.  The HW implementations want intra bc to clip to frame edges (so they can reuse the inter prediction hardware unchanged), while SW implementations want intra bc prediction to ignore frame edges (so the copy code is simpler).

Both goals can be achieved by simply telling the inter prediction HW that the frame size is a multiple of 8 during intra frames.

This is done within the specification at step 11 of [7.11.3.1](http://av1-draft-spec.argondesign.com/av1-spec/#inter-prediction-process):

> If use_intrabc is equal to 1, RefFrameWidth[ -1 ] is set equal to MiCols * MI_SIZE, RefFrameHeight[ -1 ] is set equal to MiRows * MI_SIZE, and RefUpscaledWidth[ -1 ] is set equal to MiCols * MI_SIZE. (These values are needed to avoid intrabc prediction being cropped to the frame boundaries.)

Note that normally RefFrameHeight can take any value, it is just when intra bc is in use that it is forced to be a multiple of 8.

Does this make sense?

If not, then drop me an email at peter.derivaz at argondesign.com and we can arrange a time to discuss this on the phone if you prefer.

**Comment by peterderivaz** [comment]
Sorry, didn't mean to close this before you had a chance to respond

**Comment by agrange** [comment]
Issue resolved - no action required - so closing.

Please reopen if further consideration required.
